# Generated by Django 4.2.5 on 2023-09-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='prod1', max_length=30),
            preserve_default=False,
        ),
    ]
