# Generated by Django 4.2.5 on 2023-09-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(null=True, related_name='buyers', to='school.user'),
        ),
    ]
