# Generated by Django 4.2.5 on 2023-09-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_product_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertutorial',
            name='watch_time',
            field=models.TimeField(default=0, null=True),
        ),
    ]
