# Generated by Django 4.2.5 on 2023-09-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_tutorial_video_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertutorial',
            name='watch_status',
            field=models.BooleanField(default=False),
        ),
    ]
