# Generated by Django 4.2.5 on 2023-09-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_usertutorial_watch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertutorial',
            name='last_watch',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
